services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  web:
    name: web
    driver: local
    driver_opts:
      type: none
      device: /home/disantam/data/web
      o: bind

  db:
    name: db
    driver: local
    driver_opts:
      type: none
      device: /home/disantam/data/db
      o: bind

networks:
  inception:
    name: inception
